### PR TITLE
CODEOWNERS file

### LINKED ISSUE #15: [FEAT] Add codeowners file to auto assign Kira as reviewer to PR's

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
# Related Issue/Addition to code

- Fixes #15 
- Kira doesn't get auto assigned as reviewer to PR's

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Proposed Changes
- Add Kira as reviewer to all Pr's

### CODE REVIEW

**Review by Kira272921 — APPROVED** [review]
LGTM! 🚀

**Comment by KendallDoesCoding** [comment]
> @all-contributors please add @KendallDoesCoding for doc

??

**Comment by KendallDoesCoding** [comment]
> > @all-contributors please add @KendallDoesCoding for doc
> 
> ??

Oh for the README.md, nice.. @Kira272921 I want this for one of my repos too, can you help with the setup?

**Comment by Kira272921** [comment]
@KendallDoesCoding Alright sure, I have created a discussion, ([Setting up all contributors bot](https://github.com/Kira272921/vscode-themed-portfolio/discussions/33)) where we can discuss about this

**Pull request merged**
