### PR TITLE
Add/Update templates

### LINKED ISSUE #5: [FEAT] add issue and pull request template
Here are the docs which might be helpful for creating issue and pull request templates 👇

- [How to create an issue template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository )
- [How to create pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
fixes #5 

Added
- Pull Request Template
- Feature Request Template

Updated 
- Bug report template

### CODE REVIEW

**Review by Kira272921 — APPROVED** [review]
Thanks a lot for contributing 🚀

**Comment by Kira272921** [comment]
🤔 Uh no... I didn't see that the `pull_request_template.md` wasn't in all caps. Could you create a new PR with the [`pull_request_template.md`](https://github.com/Kira272921/vscode-themed-portfolio/blob/main/.github/pull_request_template.md) renamed to `PULL_REQUEST_TEMPLATE.md`

**Comment by KendallDoesCoding** [comment]
> 🤔 Uh no... I didn't see that the `pull_request_template.md` wasn't in all caps. Could you create a new PR with the [`pull_request_template.md`](https://github.com/Kira272921/vscode-themed-portfolio/blob/main/.github/pull_request_template.md) renamed to `PULL_REQUEST_TEMPLATE.md`

Hi, the format is required to be lowercase, not uppercase as per the [docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository).
image.

In all repos I see, it's in lowercase, if you want you can still make it upper-case, no harm but it's preferred you dont :)

**Comment by Kira272921** [comment]
@KendallDoesCoding Ahhh ok ok :+1:

**Pull request merged**
