### PR TITLE
Open github url instead of portfolio

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
# Related Issue/Addition to code

- I don't want it to open my portfolio, it's better to open my github where user can see my contributions, project code, etc.

## Type of change
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Proposed Changes
- Update url from portfolio to github
- change 2

# Additional Info
- any additional info for context

## Checklist:

- [ ] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

# Screenshots

Original | Updated
:----------------------:|:-----------:
** original screenshot  | ** updated screenshot **

### CODE REVIEW

**Review by Kira272921 — COMMENTED** [review]
Hey! This entire process is automated so the edits made in the `README.md` would be changed afterward by all contributors bot. Instead, change it in the [`.all-contributorsrc`](https://github.com/Kira272921/vscode-themed-portfolio/blob/main/.all-contributorsrc) file. On [line 35](https://github.com/Kira272921/vscode-themed-portfolio/blob/main/.all-contributorsrc#L35) of  [`.all-contributorsrc`](https://github.com/Kira272921/vscode-themed-portfolio/blob/main/.all-contributorsrc) file, make your changes 😄

**Comment by KendallDoesCoding** [comment]
> 

Ok will make a new PR.

**Review by KendallDoesCoding — COMMENTED** [review]
It says 4 files changes, I commited my last PR in main, so don't know if I messed up anything here. Will I need to delete my fork repo and make a new fork with these changes @Kira272921 ?

**Comment by Kira272921** [comment]
@KendallDoesCoding I'll merge this PR for now, if there is some issue I will let you know.

**Review by Kira272921 — APPROVED** [review]

**Comment by KendallDoesCoding** [comment]
Ok. Thanks

**Pull request merged**
